# Generated by Django 5.2.8 on 2025-11-11 08:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('money', models.IntegerField(default=0)),
                ('comment', models.TextField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactioncategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactionstatus')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactionsubcategory')),
                ('transactionType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactiontype')),
            ],
        ),
    ]
