# Generated by Django 5.2.8 on 2025-11-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
