# Generated by Django 5.2.8 on 2025-11-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_subcategory_transaction_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionType',
            new_name='transaction_type',
        ),
    ]
