# Generated by Django 5.2.8 on 2025-11-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_transactiontype_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='t_type',
        ),
    ]
