# Generated by Django 5.2.8 on 2025-11-12 07:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_rename_subcategory_categorysubcategory_sub_category_and_more'),
        ('transaction', '0004_rename_transaction_type_transaction_t_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactioncategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(default=None, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactionstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactionsubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.transactiontype', verbose_name='Тип'),
        ),
    ]
