# Generated by Django 5.2.8 on 2025-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_options_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, default=None, verbose_name='Комментарий'),
        ),
    ]
