# Generated by Django 5.2.8 on 2025-11-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactioncategory')),
                ('transaction_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactionsubcategory')),
            ],
            options={
                'unique_together': {('transaction_subcategory', 'transaction_category')},
            },
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactioncategory')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactiontype')),
            ],
            options={
                'unique_together': {('transaction_category', 'transaction_type')},
            },
        ),
    ]
