# Generated by Django 5.2.8 on 2025-11-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubcategory',
            old_name='transaction_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorysubcategory',
            old_name='transaction_subcategory',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='categorytype',
            old_name='transaction_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorytype',
            old_name='transaction_type',
            new_name='t_type',
        ),
        migrations.AlterUniqueTogether(
            name='categorysubcategory',
            unique_together={('subcategory', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytype',
            unique_together={('category', 't_type')},
        ),
    ]
