# Generated by Django 5.2.8 on 2025-11-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_rename_transaction_category_categorysubcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubcategory',
            old_name='subcategory',
            new_name='subCategory',
        ),
        migrations.RenameField(
            model_name='categorytype',
            old_name='t_type',
            new_name='tType',
        ),
        migrations.AlterUniqueTogether(
            name='categorysubcategory',
            unique_together={('subCategory', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytype',
            unique_together={('category', 'tType')},
        ),
    ]
