# Generated by Django 5.2.8 on 2025-11-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_rename_subcategory_categorysubcategory_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubcategory',
            old_name='subCategory',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='categorytype',
            old_name='tType',
            new_name='t_type',
        ),
        migrations.AlterUniqueTogether(
            name='categorysubcategory',
            unique_together={('sub_category', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytype',
            unique_together={('category', 't_type')},
        ),
    ]
