# Generated by Django 5.2.8 on 2025-11-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_rename_subcategory_categorysubcategory_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysubcategory',
            options={'verbose_name': 'Связь категория-подкатегория', 'verbose_name_plural': 'Связи категория-подкатегория'},
        ),
        migrations.AlterModelOptions(
            name='categorytype',
            options={'verbose_name': 'Связь категория-тип', 'verbose_name_plural': 'Связи категория-тип'},
        ),
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='transactionstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='transactionsubcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='categorysubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactioncategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categorysubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactionsubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactioncategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='t_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.transactiontype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transactionstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transactionsubcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
